### PR TITLE
ast27: prefix exported symbols

### LINKED ISSUE #139: test_ignores and test_convert_strs fail on ppc64
Hi,

in openSUSE packaging we experience two test fails on the  ppc64 architecture (only):

```
=================================== FAILURES ===================================
_________________________________ test_ignores _________________________________

    def test_ignores():
        expected = [
            (2, ''),
            (5, ''),
            (8, '[excuse]'),
            (9, '=excuse'),
            (10, ' [excuse]'),
            (11, ' whatever'),
        ]
    
        for version in range(MIN_VER, NEXT_VER):
            tree = _ast3._parse(ignores, "<ignores>", "exec", version)
            assert [(ti.lineno, ti.tag) for ti in tree.type_ignores] == expected
            with pytest.raises(SyntaxError):
                _ast3._parse("pass  # type: ignoreé\n", "<ignores>", "exec", version)
    
    
        tree = _ast27.parse(ignores, "<ignores>", "exec")
>       assert [(ti.lineno, ti.tag) for ti in tree.type_ignores] == expected
E       AssertionError: assert [] == [(2, ''),\n (5, ''),\n (8, '[excuse]'),\n (9, '=excuse'),\n (10, ' [excuse]'),\n (11, ' whatever')]
E         Right contains 6 more items, first extra item: (2, '')
E         Full diff:
E           [
E         -  ,
E         +  (2,
E         +   ''),
E         +  (5,
E         +   ''),
E         +  (8,
E         +   '[excuse]'),
E         +  (9,
E         +   '=excuse'),
E         +  (10,
E         +   ' [excuse]'),
E         +  (11,
E         +   ' whatever'),
E           ]

ast3/tests/test_basics.py:223: AssertionError
______________________________ test_convert_strs _______________________________

    def test_convert_strs():
        ast = _ast27.parse(basic_py2, "<basic_py2>", "exec")
        tree = typed_ast.conversions.py2to3(ast)
>       assert tree.body[0].value.kind == ""
E       IndexError: list index out of range

ast3/tests/test_basics.py:305: IndexError
========================= 2 failed, 13 passed in 0.45s =========================
```

[Full build log attached](https://github.com/python/typed_ast/files/4639031/typed-ast-ppc64.log)

Maybe you have an idea what's going on? We disabled the two tests for unblock other package builds as temporary solution.

### LINKED ISSUE #151: ast27 gives syntax error for valid code on s390x
This examples comes from [the test suite of black](https://github.com/psf/black/blob/20.8b1/tests/data/python2.py)
```python
from typed_ast import ast27

ast27.parse('''#!/usr/bin/env python2.7

def function((_globals, _locals)):
    print _globals, _locals
''')
```

Results in:

```python
Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-46b135e3f4de>", line 1, in <module>
    ast27.parse('''#!/usr/bin/env python2.7

  File "/usr/lib/python3.8/site-packages/typed_ast/ast27.py", line 50, in parse
    return _ast27.parse(source, filename, mode)

  File "<unknown>", line 3
SyntaxError: can't assign to ()
```
The same code parses fine on python 2.7.18.

This is with typed-ast 1.4.1. It only happens on s390x on Alpine Linux edge. 

Let me know if you need more information.

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #151 and (probably) fixes #139

Linking shenanigans caused ast27 to link against Python's `asdl.c`, instead of `ast27/Python/asdl.c`. Python's `asdl.c` uses `Py_ssize_t` for `asdl_seq`'s size whereas `ast27/Python/asdl.c` uses `int`. This means we were interpreting memory differently in `asdl.c` and `ast.c`. On 64-bit big-endian systems, this caused us to misplace `asdl.c`'s writes to `asdl_seq->size`, since `Py_ssize_t` is eight bytes, but `int` is four. The fix mirrors what we do in ast3, that is, manually namespace definitions to avoid linking conflicts.

### CODE REVIEW

**Comment by sebix** [comment]
I can confirm this fixes both the ppc64 and the s390x builds / tests that we perform in openSUSE for packaging! Thanks for your work!

**Comment by JelleZijlstra** [comment]
Is there a reason for the difference between typed_ast's and Python's asdl.c? Could there (shudders) be a bug in typed_ast that comes up only if you try to make a tuple with more than INT_MAX elements?

**Review by JelleZijlstra — APPROVED** [review]

File: ast27/Include/asdl.h [hunk 1]
```diff
@@ -28,11 +28,11 @@ typedef struct {
...
-#define asdl_seq_new _Py_asdl_seq_new
-#define asdl_int_seq_new _Py_asdl_int_seq_new
+#define asdl_seq_new _Ta27_asdl_seq_new
+#define asdl_int_seq_new _Ta27_asdl_int_seq_new
 #else
-#define _Py_asdl_seq_new asdl_seq_new
-#define _Py_asdl_int_seq_new asdl_int_seq_new
+#define _Ta27_asdl_seq_new asdl_seq_new
+#define _Ta27_asdl_int_seq_new asdl_int_seq_new
 #endif
```
Comment (gvanrossum) [inline ast27/Include/asdl.h:36]: Why even have the if/else here? We don't support Python 3.3 or before, do we?

**Review by gvanrossum — COMMENTED** [review]
Thanks to you both for finding this!

File: ast27/Include/asdl.h (hunk 1 above)
Comment (hauntsaninja) [reply ast27/Include/asdl.h:36]: Nope, I was just making a commit to remove this!

**Comment by hauntsaninja** [comment]
@JelleZijlstra The struct has the same declaration in `ast27/Python/asdl.c` as in Python 2.7's `asdl.c`, so if there is an issue in parsing a file with more than INT_MAX of a thing, it probably applies to Python 2.7 as well.

...That said, it looks like there is a difference in the signature of `asdl_seq_new`. In ast27, it's: `asdl_seq *asdl_seq_new(Py_ssize_t size, PyArena *arena);` whereas in Python 2.7 it's `asdl_seq *asdl_seq_new(int size, PyArena *arena);`. This goes back to a3f63eb6, which introduced `ast27/Python/asdl.c`. I'm not sure this matters, but I can change it back for consistency and peaceful sleeping.

Finally, looking at the macros also made me realise that ast27's ast.c currently prefers to use the macro asdl_seq_new instead of _Ta27_asdl_seq_new. On the other hand, being clever and not using obviously namespaced symbols is what caused the bug, so maybe I should get rid of the asdl_seq_new macro altogether. On the third hand, this PR has already been tested on various systems I don't have access to and I'm reluctant to do refactoring solely for style.

Let me know!

**Comment by JelleZijlstra** [comment]
Thanks for the explanation! It's probably not worth it to go through any more refactoring for Python 2.7 code—let's just let 2.7 die a peaceful death.

**Review by gvanrossum — APPROVED** [review]
Excellent!

Once this is landed I'll try to make a new release (hope I still remember how to).

**Comment by hauntsaninja** [comment]
As far as I can tell https://github.com/python/typed_ast/blob/master/release_process.md is up to date, although it's missing a mention of Python 3.9 :-)
